### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Rafcin** [Dokany/mapExplorerRobot#1]
Are you using a Roboclaw for motor control? And if so is it with encoders? Also could you substitute a IMU with a Stereo Cam like the Zed instead? It saves space and Arduinos are slow.

**Comment by Dokany** [comment]
We're using the [Pololu TReX DMC01](https://www.pololu.com/product/777) dual motor controller that doesn't have wheel encoders. And we can definitely use ZED instead of the IMU, but we didn't have access to one for this project.

**Comment by Rafcin** [comment]
I'm attempting to do that with a zed at the moment

**Comment by Dokany** [comment]
Keep us updated with your progress!
